Subject = "Password Reset Request"
Subject2 = "New Password"

[PassEmailTitle]
description = "Password Reset Request Template"
other = "Hello {{.Name}},"

[Key]
description = "Confirmation key"
other = "We got request for Password Reset. There is the confirmation code: <br><br><b> {{.Password}} </b><br><br> If you do not made this request, please contact with support"


[NewPass]
description = "New password"
other = "There is your new password: <br><br><b> {{.Password}} </b><br><br> "
