Subject = "Запрос на сброс пароля"
Subject2 = "Новый пароль"

[PassEmailTitle]
description = "Password Reset Request Template"
other = "Здравствуйте {{.Name}},"

[Key]
description = "Confirmation key"
other = "Мы получили запрос на сброс пароля. Это Ваш код подтверждения: <br><br><b> {{.Password}} </b><br><br> Если Вы не запрашивали сброс пароля, пожалуйста свяжитесь со службой поддержки"


[NewPass]
description = "New password"
other = "Ваш новый пароль: <br><br><b> {{.Password}} </b><br><br> "
