[database]
password = '$2a##fC96Z5BttwpBQA_OB6sCUGsUv1kjuOd4gP2SarLqMmA'

[email]
password = '$2a##yQQ1HiWa2gSVtaqx_rkyks3Y1lyPQ8pJV9qdtisD2Sk'

[masterservice]
host = ''
port = ''

[sentry]
sentry = false

[server]
debug = true
domain = ''
internal_host = ''
ip = '127.0.0.1'
logdir = '/var/gufo/log/'
port = '8090'
sessions = true
sign = '0npjp3xP7_JJcg6P6ZfhXxZoIMmG_-xnveoSts63htZNfyOCSRm-kpEIMeVtpRHV'
sysdir = '/var/gufo/'
tempdir = '/var/gufo/templates/'
