[sentry]
sentry = false
#debug = true
#dsn = ''
#flush = 5
#trace = 1.0
#tracing = true

[server]
debug = true
domain = ''
internal_host = ''
ip = '127.0.0.1'
logdir = '/var/gufo/log/'
port = '8090'
sign = ''
sysdir = '/var/gufo/'
tempdir = '/var/gufo/templates/'
sessions = true

[masterservice]
host = ''
port = ''
